feat: add stats page
ipfs-shipyard/service-worker-gateway-2019-poc pull request #11
Opened 2018-05-29 15:25 UTC by vasco-santos

Created the MVP Stats Page for the IPFS Node running in the service worker.

<img width="1002" alt="screen shot 2018-05-29 at 15 04 15" src="https://user-images.githubusercontent.com/7295071/40668588-d57bb626-635c-11e8-8f0e-c09d1e0d887c.png">

Closes #10

2018-05-29 16:48 UTC, hugomrdias requested changes

2018-05-29 16:48 UTC, hugomrdias commented on src/index.js
> +          .then((values) => {
```js
.then(([id,stat]) => {
```

2018-05-29 16:48 UTC, hugomrdias commented on src/index.js
>    })
add catch

2018-05-29 16:48 UTC, hugomrdias commented on src/index.js
>      node.get()
return here instead of creating a new Promise

2018-05-29 16:48 UTC, hugomrdias commented on src/index.js
> +        resolve(resp)
and also return here instead of resolving

2018-05-30 10:34 UTC, fsdiogo commented on src/index.js
> +        date: `${d.getFullYear()}/${d.getMonth()}/${d.getDate()}`,
As you're doing this twice, you could abstract it to a tiny method that returns the date and time. But up to you.

2018-05-30 10:36 UTC, fsdiogo commented on src/stats-view/style.js
> +module.exports = `html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}a{background-color:transparent}a:active,a:hover{outline:0}strong{font-weight:700}bu
This is a bit odd, a `.padding` class that changes the margin 😛

2018-05-30 10:43 UTC, hugomrdias approved these changes

2018-05-30 10:49 UTC, fsdiogo approved these changes
👍

2018-05-30 10:52 UTC, merged